### ISSUE TITLE
confused of your data input length  ?

### ISSUE THREAD

**Issue by ckxkexing** [wala/blanca#1]
I read your paper, but I'm still confused. Excuse me, does the input length of data exceed the maximum input length of Bert (512)? Do you also cut off the excess part directly?

Because the code text is often long, I am confused about how to understand long text code with Bert.

Looking forward to your reply, thank you!

**Comment by ksrinivs64** [comment]
We used the sentence transformers library from SBERT (https://www.sbert.net/) to create embeddings for sentences.  Hope that helps!
